catalog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^movies/$', views.MovieListView.as_view(), name='movies'),
    url(r'^movie/(?P<pk>\d+)$', views.MovieDetailView.as_view(), name='movie-detail'),
    url(r'^directors/$', views.DirectorListView.as_view(), name='directors'),
    url(r'^director/(?P<pk>\d+)$', views.DirectorDetailView.as_view(), name='director-detail'),
    url(r'^actors/$', views.ActorListView.as_view(), name='actors'),
    url(r'^actor/(?P<pk>\d+)$', views.ActorDetailView.as_view(), name='actor-detail'),
]

movie_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^catalog/', include('catalog.urls')),
        url(r'^$', RedirectView.as_view(url='/catalog/', permanent=True)),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Genre(models.Model):
    """
    Model representing a book genre (e.g. Science Fiction, Non Fiction).
    """
    name = models.CharField(max_length=200, help_text="Enter a movie genre (e.g. Science Fiction, Action, Drama etc.)")
    
    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.name

class Actor(models.Model):
    """
    Model representing an Actor (e.g. Tom Cruise, Daniel Radcliffe).
    """
    name = models.CharField(max_length=200, help_text="Enter a movie Actors Name (e.g. Tom Cruise, Daniel Radcliff).")
    last_name = models.CharField(max_length=100)
    bio = models.TextField(max_length=1000, default='No Bio Information Set', help_text="Enter a brief Character Bio or Resume")

    def get_absolute_url(self):
        """
        Returns the url to access a particular director instance.
        """
        return reverse('actor-detail', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return '%s %s' % (self.name, self.last_name)

from django.core.urlresolvers import reverse #Used to generate URLs by reversing the URL patterns

class Movie(models.Model):
    """
    Model representing a book (but not a specific copy of a book).
    """
    title = models.CharField(max_length=200)
    release_date = models.DateField(null=True, blank=True)
    director = models.ForeignKey('Director', on_delete=models.SET_NULL, null=True)
    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file.
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the movie, NO SPOILERS")
    trivia = models.TextField(max_length=1000, null=True, blank=True, help_text="Any related facts or trivia relating to this movie")
    youtubeid = models.CharField('Youtube ID', max_length=40, null=True, blank=True, help_text='Unique youtube video id for the trailer <a href="https://www.isbn-international.org/content/what-isbn">Youtube ID</a>')
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this movie")
    actor = models.ManyToManyField(Actor, help_text="Select an actor for this movie")
    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    
    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.title
    
    
    def get_absolute_url(self):
        """
        Returns the url to access a particular movie instance.
        """
        return reverse('movie-detail', args=[str(self.id)])

    def display_genre(self):
        """
        Creates a string for the Genre. This is required to display genre in Admin.
        """
        return ', '.join([ genre.name for genre in self.genre.all()[:3] ])
    display_genre.short_description = 'Genre'
    
    def display_actors(self):
        """
        Creates a string for the Cast.
        """
        return ', '.join([ actor.name for actor in self.actor.all()[:3] ])
    display_actors.short_description = 'Cast'


class Director(models.Model):
    """
    Model representing an director.
    """
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)
    
    def get_absolute_url(self):
        """
        Returns the url to access a particular director instance.
        """
        return reverse('director-detail', args=[str(self.id)])
    

    def __str__(self):
        """
        String for representing the Model object.
        """
        return '%s %s' % (self.first_name, self.last_name)
    
    def display_full_name(self):
            """
            Creates a string for the name of this Director.
            """
            return ' '.join([ self.first_name, self.last_name ])
    display_full_name.short_description = 'Name'

class Character(models.Model):
    """
    Model representing an author.
    """
    actor = models.ForeignKey(Actor, related_name='films')
    movie = models.ForeignKey(Movie, related_name='actors')
    character = models.CharField(max_length=255)

    def __str__(self):
        """
        String for representing the Model object.
        """
        return '%s (%s - played by %s)' % (self.character, self.movie, self.actor)

catalog/views.py
from django.shortcuts import render
from .models import Movie, Director, Actor, Genre

def index(request):
    """
    View function for home page of site.
    """
    my_parameter = 'dan'
    # Generate counts of some of the main objects
    num_movies=Movie.objects.all().count()
    num_directors=Director.objects.count()  # The 'all()' is implied by default.
    num_actors=Actor.objects.count()  # The 'all()' is implied by default.
    num_genres=Genre.objects.count()  # The 'all()' is implied by default.
    num_daniel=Actor.objects.filter(name__icontains=my_parameter) # The 'all()' is implied by default.
    
    # Render the HTML template index.html with the data in the context variable
    return render(
        request,
        'index.html',
        context={'num_movies':num_movies,'num_directors':num_directors, 'num_actors':num_actors, 'num_genres':num_genres, 'num_daniel':num_daniel   },
    )
from django.views import generic

class MovieListView(generic.ListView):
    model = Movie
    
    paginate_by = 3
    def get_queryset(self):
        # return Movie.objects.filter(title__icontains='water')[:5] # get 5 Movies with the string potter in the name
        return Movie.objects.all().order_by('-release_date')
        
        
    # def last_ten(self):
    #     return Movie.objects.filter(since=since).order_by('-id')[:10]
        # return last_ten_in_ascending_order = reversed(last_ten)

class MovieDetailView(generic.DetailView):
    model = Movie
    
class DirectorListView(generic.ListView):
    model = Director
    
    paginate_by = 4
    def get_queryset(self):
        # return Movie.objects.filter(title__icontains='water')[:5] # get 5 Movies with the string potter in the name
        return Director.objects.all()
        
        
    # def last_ten(self):
    #     return Movie.objects.filter(since=since).order_by('-id')[:10]
        # return last_ten_in_ascending_order = reversed(last_ten)

class DirectorDetailView(generic.DetailView):
    model = Director

class ActorListView(generic.ListView):
    model = Actor
    paginate_by = 8
    def get_queryset(self):
        # return Movie.objects.filter(title__icontains='water')[:5] # get 5 Movies with the string potter in the name
        return Actor.objects.all()
        
        
    # def last_ten(self):
    #     return Movie.objects.filter(since=since).order_by('-id')[:10]
        # return last_ten_in_ascending_order = reversed(last_ten)

class ActorDetailView(generic.DetailView):
    model = Actor
    
    
    

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/main.css' %}?{% now 'U' %}">
</head>

<body>

  <header class="container-fluid">
      <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Project name</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#">About</a></li>
              <li><a href="#">Contact</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li role="separator" class="divider"></li>
                  <li class="dropdown-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="active"><a href="./">Default <span class="sr-only">(current)</span></a></li>
              <li><a href="../navbar-static-top/">Static top</a></li>
              <li><a href="../navbar-fixed-top/">Fixed top</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>
  </header>
  <div class="container-fluid">

    <div class="row">
      <div class="col-xs-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'movies' %}">All movies</a></li>
          <li><a href="{% url 'directors' %}">All directors</a></li>
          <li><a href="{% url 'actors' %}">All actors</a></li>
      </ul>
     {% endblock %}
      </div>
      <div class="col-xs-10 ">
      {% block content %}{% endblock %}
      {% block pagination %}
        {% if is_paginated %}
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
        {% endif %}
      {% endblock %}
      </div>
    </div>
    
  </div>
</body>
</html>

catalog/templates/catalog/actor_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Actor Profile: {{ actor.name }} {{actor.last_name}}</h1>
    
    <p><strong>Bio:</strong> {{ actor.bio }}</p>
    <p><strong>Films starred in:</strong></p>
    <ul>
          {% for movie in actor.movie_set.all %}
          <li>
              <a href="{{ movie.get_absolute_url }}">{{movie.title}}</a>
          </li>
          {% empty %}
             <!-- no entries -->
          {% endfor %}
</ul>
{% endblock %}

catalog/templates/catalog/actor_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Actor List</h1>

    {% if actor_list %}
    <ul>

      {% for actor in actor_list %}
      <li>
        <a href="{{ actor.get_absolute_url }}">{{ actor.name }} {{ actor.last_name }}</a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no movies in the catalog.</p>
    {% endif %}   
{% endblock %}
The view passes the context (list of directors) 

catalog/templates/catalog/director_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Director Name: {{ director.first_name }} {{ director.last_name }}</h1>
    
    <p><strong>Born:</strong> {{ director.date_of_birth }}</p>

{% endblock %}

catalog/templates/catalog/director_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Director List</h1>

    {% if director_list %}
    <ul>

      {% for director in director_list %}
      <li>
        <a href="{{ director.get_absolute_url }}">{{ director.first_name }} {{ director.last_name }}</a> 
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no directors to show.</p>
    {% endif %}       
{% endblock %}
The view passes the context (list of directors) 

catalog/templates/catalog/movie_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Title: {{ movie.title }}</h1>
    
    <p><strong>Summary:</strong> {{ movie.summary }}</p>
    <p><strong>Genres:</strong> {% for genre in movie.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  
    <p><strong>Release date:</strong> {{ movie.release_date }}</p> 
    <p><strong>Official Trailer:</strong></p>
    <div class="video-container">
        <iframe width="500" height="300" src="https://www.youtube.com/embed/{{ movie.youtubeid }}" frameborder="0" allowfullscreen></iframe>
    </div>
    <p><strong>Author:</strong> <a href=""><a href="">{{ movie.director }}</a></p> <!-- author detail link not yet defined -->
    <p><strong>Cast:</strong> {% for actor in movie.actor.all %} {{ actor }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  

{% endblock %}

catalog/templates/catalog/movie_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Movie List</h1>

    {% if movie_list %}
    <ul>

      {% for movie in movie_list %}
      <li>
        <a href="{{ movie.get_absolute_url }}">{{ movie.title }}</a> ({{ movie.release_date }})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no movies in the catalog.</p>
    {% endif %}       
{% endblock %}
The view passes the context (list of movies) 

catalog/templates/index.html
{% extends "base_generic.html" %}
 {% block title %}<title>App Library</title>{% endblock %}
{% block content %}
<h1>Local Library Home</h1>

  <p>Welcome to <em>LocalLibrary</em>, a very basic Django website developed as a tutorial example on the Mozilla Developer Network.</p>

<h2>Dynamic content</h2>

  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Movies:</strong> {{ num_movies }}</li>
    <li><strong>Actors:</strong> {{ num_actors }}</li>
    <li><strong>Genres:</strong> {{ num_genres }}</li>
    <li><strong>Directors:</strong> {{ num_directors }}</li>
    <li><strong>Number of Daniels:</strong> {{ num_daniel|length }} Dans</li>
  </ul>
  <h2>Dynamic Daniels</h2>

  <ul>
{% for daniel in num_daniel %}
<li>{{ daniel }}</li>
{% endfor %}
</ul>
  

{% endblock %}